version: "3.9"

services:
  discord-bot:
    container_name: discord_bot
    build:
      context: https://github.com/streLiQQ/discord-bot.git
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      APP_ID: ${APP_ID}
      SERVER_ID: ${SERVER_ID}
      WEATHER_API: ${WEATHER_API}
